server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  rabbitmq:
    host: 192.168.71.132
    virtual-host: /xiaoyao
    username: xiaoyao
    password: xiaoyao
    listener:
      simple:
        prefetch: 1
        concurrency: 4
        acknowledge-mode: manual
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  elasticsearch:
    rest:
      uris: 192.168.71.132:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true

