server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.71.132:3306/guli_ums
    username: root
    password: root
  redis:
    host: 192.168.71.132
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/ums/**/*.xml
  type-aliases-package: com.atguigu.gmall.ums.entity
  global-config:
    db-config:
      id-type: auto